// ═══════════════════════════════════════════════════════════════════════════
// JUSTINIANUS.AI — TIPOS DO BANCO DE DADOS (SUPABASE)
// Gerado a partir do schema SQL consolidado v2.0
// ═══════════════════════════════════════════════════════════════════════════

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      organizacoes: {
        Row: {
          id: string;
          nome: string;
          tipo_organizacao: 'escritorio_advocacia' | 'departamento_juridico' | 'plataforma';
          configuracoes: Json;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          nome: string;
          tipo_organizacao: 'escritorio_advocacia' | 'departamento_juridico' | 'plataforma';
          configuracoes?: Json;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          nome?: string;
          tipo_organizacao?: 'escritorio_advocacia' | 'departamento_juridico' | 'plataforma';
          configuracoes?: Json;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      membros_organizacao: {
        Row: {
          id: string;
          organizacao_id: string;
          usuario_id: string;
          papel: string;
          permissoes: Json;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          usuario_id: string;
          papel: string;
          permissoes?: Json;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          usuario_id?: string;
          papel?: string;
          permissoes?: Json;
          criado_em?: string;
        };
      };
      politicas_organizacao: {
        Row: {
          id: string;
          organizacao_id: string;
          chave_politica: string;
          valor_politica: Json;
          descricao: string | null;
          ativo: boolean;
          atualizado_por: string | null;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          chave_politica: string;
          valor_politica: Json;
          descricao?: string | null;
          ativo?: boolean;
          atualizado_por?: string | null;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          chave_politica?: string;
          valor_politica?: Json;
          descricao?: string | null;
          ativo?: boolean;
          atualizado_por?: string | null;
          atualizado_em?: string;
        };
      };
      eventos_dominio: {
        Row: {
          id: string;
          organizacao_id: string;
          nome_evento: string;
          tipo_entidade: string | null;
          id_entidade: string | null;
          payload: Json;
          id_correlacao: string | null;
          id_causacao: string | null;
          usuario_ator_id: string | null;
          tipo_agente_ator: string | null;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          nome_evento: string;
          tipo_entidade?: string | null;
          id_entidade?: string | null;
          payload?: Json;
          id_correlacao?: string | null;
          id_causacao?: string | null;
          usuario_ator_id?: string | null;
          tipo_agente_ator?: string | null;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          nome_evento?: string;
          tipo_entidade?: string | null;
          id_entidade?: string | null;
          payload?: Json;
          id_correlacao?: string | null;
          id_causacao?: string | null;
          usuario_ator_id?: string | null;
          tipo_agente_ator?: string | null;
          criado_em?: string;
        };
      };
      clientes: {
        Row: {
          id: number;
          organizacao_id: string;
          tipo_cliente: 'pessoa_fisica' | 'pessoa_juridica';
          nome: string;
          cpf_cnpj: string | null;
          email: string | null;
          telefone: string | null;
          endereco: Json | null;
          metadados: Json;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: number;
          organizacao_id: string;
          tipo_cliente: 'pessoa_fisica' | 'pessoa_juridica';
          nome: string;
          cpf_cnpj?: string | null;
          email?: string | null;
          telefone?: string | null;
          endereco?: Json | null;
          metadados?: Json;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: number;
          organizacao_id?: string;
          tipo_cliente?: 'pessoa_fisica' | 'pessoa_juridica';
          nome?: string;
          cpf_cnpj?: string | null;
          email?: string | null;
          telefone?: string | null;
          endereco?: Json | null;
          metadados?: Json;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      usuarios_cliente: {
        Row: {
          id: string;
          organizacao_id: string;
          cliente_id: number;
          usuario_id: string;
          portal_habilitado: boolean;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          cliente_id: number;
          usuario_id: string;
          portal_habilitado?: boolean;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          cliente_id?: number;
          usuario_id?: string;
          portal_habilitado?: boolean;
          criado_em?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          organizacao_id: string;
          tipo_cliente: 'pessoa_fisica' | 'pessoa_juridica';
          nome: string;
          email: string | null;
          telefone: string | null;
          tipo_servico: 'consultivo' | 'contencioso' | 'administrativo' | 'consensual';
          nivel_urgencia: 'baixa' | 'media' | 'alta' | 'critica';
          status: 'novo' | 'em_analise' | 'qualificado' | 'recusado' | 'convertido';
          origem: 'formulario' | 'email' | 'upload' | 'api' | 'manual' | 'indicacao' | null;
          referencia_origem: string | null;
          cliente_id: number | null;
          caso_convertido_id: number | null;
          descricao_inicial: string | null;
          metadados: Json;
          criado_por: string | null;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          tipo_cliente: 'pessoa_fisica' | 'pessoa_juridica';
          nome: string;
          email?: string | null;
          telefone?: string | null;
          tipo_servico: 'consultivo' | 'contencioso' | 'administrativo' | 'consensual';
          nivel_urgencia?: 'baixa' | 'media' | 'alta' | 'critica';
          status?: 'novo' | 'em_analise' | 'qualificado' | 'recusado' | 'convertido';
          origem?: 'formulario' | 'email' | 'upload' | 'api' | 'manual' | 'indicacao' | null;
          referencia_origem?: string | null;
          cliente_id?: number | null;
          caso_convertido_id?: number | null;
          descricao_inicial?: string | null;
          metadados?: Json;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          tipo_cliente?: 'pessoa_fisica' | 'pessoa_juridica';
          nome?: string;
          email?: string | null;
          telefone?: string | null;
          tipo_servico?: 'consultivo' | 'contencioso' | 'administrativo' | 'consensual';
          nivel_urgencia?: 'baixa' | 'media' | 'alta' | 'critica';
          status?: 'novo' | 'em_analise' | 'qualificado' | 'recusado' | 'convertido';
          origem?: 'formulario' | 'email' | 'upload' | 'api' | 'manual' | 'indicacao' | null;
          referencia_origem?: string | null;
          cliente_id?: number | null;
          caso_convertido_id?: number | null;
          descricao_inicial?: string | null;
          metadados?: Json;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      qualificacoes_lead: {
        Row: {
          id: string;
          organizacao_id: string;
          lead_id: string;
          classificacao: string | null;
          nivel_risco: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          area_juridica: string[] | null;
          prazo_critico: string | null;
          data_prescricao: string | null;
          alerta_prescricao_enviado: boolean;
          resumo_executivo: string | null;
          fatos_principais: Json | null;
          estrategia_recomendada: string | null;
          confianca_ia: number | null;
          id_execucao_ia: string | null;
          pontuacao_fundamentacao: number | null;
          pontuacao_consistencia: number | null;
          decisao: 'aceito' | 'recusado' | 'pendente';
          motivo_recusa: string | null;
          validado_por: string | null;
          validado_em: string | null;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          lead_id: string;
          classificacao?: string | null;
          nivel_risco?: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          area_juridica?: string[] | null;
          prazo_critico?: string | null;
          data_prescricao?: string | null;
          alerta_prescricao_enviado?: boolean;
          resumo_executivo?: string | null;
          fatos_principais?: Json | null;
          estrategia_recomendada?: string | null;
          confianca_ia?: number | null;
          id_execucao_ia?: string | null;
          pontuacao_fundamentacao?: number | null;
          pontuacao_consistencia?: number | null;
          decisao?: 'aceito' | 'recusado' | 'pendente';
          motivo_recusa?: string | null;
          validado_por?: string | null;
          validado_em?: string | null;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          lead_id?: string;
          classificacao?: string | null;
          nivel_risco?: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          area_juridica?: string[] | null;
          prazo_critico?: string | null;
          data_prescricao?: string | null;
          alerta_prescricao_enviado?: boolean;
          resumo_executivo?: string | null;
          fatos_principais?: Json | null;
          estrategia_recomendada?: string | null;
          confianca_ia?: number | null;
          id_execucao_ia?: string | null;
          pontuacao_fundamentacao?: number | null;
          pontuacao_consistencia?: number | null;
          decisao?: 'aceito' | 'recusado' | 'pendente';
          motivo_recusa?: string | null;
          validado_por?: string | null;
          validado_em?: string | null;
          criado_em?: string;
        };
      };
      casos: {
        Row: {
          id: number;
          organizacao_id: string;
          cliente_id: number;
          lead_id: string | null;
          titulo: string;
          numero_interno: string | null;
          numero_externo: string | null;
          tipo_caso: 'contencioso' | 'consultivo' | 'administrativo' | 'consensual';
          area_juridica: string[] | null;
          status_caso: 'ativo' | 'suspenso' | 'em_execucao' | 'encerrado';
          fase_atual: 'captacao' | 'qualificacao' | 'analise' | 'acao' | 'registro' | null;
          usuario_responsavel_id: string | null;
          ids_usuarios_equipe: string[] | null;
          portal_cliente_habilitado: boolean;
          valor_causa: number | null;
          tribunal: string | null;
          id_perfil_juiz: string | null;
          aberto_em: string;
          encerrado_em: string | null;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: number;
          organizacao_id: string;
          cliente_id: number;
          lead_id?: string | null;
          titulo: string;
          numero_interno?: string | null;
          numero_externo?: string | null;
          tipo_caso: 'contencioso' | 'consultivo' | 'administrativo' | 'consensual';
          area_juridica?: string[] | null;
          status_caso?: 'ativo' | 'suspenso' | 'em_execucao' | 'encerrado';
          fase_atual?: 'captacao' | 'qualificacao' | 'analise' | 'acao' | 'registro' | null;
          usuario_responsavel_id?: string | null;
          ids_usuarios_equipe?: string[] | null;
          portal_cliente_habilitado?: boolean;
          valor_causa?: number | null;
          tribunal?: string | null;
          id_perfil_juiz?: string | null;
          aberto_em?: string;
          encerrado_em?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: number;
          organizacao_id?: string;
          cliente_id?: number;
          lead_id?: string | null;
          titulo?: string;
          numero_interno?: string | null;
          numero_externo?: string | null;
          tipo_caso?: 'contencioso' | 'consultivo' | 'administrativo' | 'consensual';
          area_juridica?: string[] | null;
          status_caso?: 'ativo' | 'suspenso' | 'em_execucao' | 'encerrado';
          fase_atual?: 'captacao' | 'qualificacao' | 'analise' | 'acao' | 'registro' | null;
          usuario_responsavel_id?: string | null;
          ids_usuarios_equipe?: string[] | null;
          portal_cliente_habilitado?: boolean;
          valor_causa?: number | null;
          tribunal?: string | null;
          id_perfil_juiz?: string | null;
          aberto_em?: string;
          encerrado_em?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      prazos: {
        Row: {
          id: string;
          organizacao_id: string;
          caso_id: number;
          tipo_prazo: string;
          descricao: string;
          origem: 'publicacao' | 'intimacao' | 'contrato' | 'manual' | 'detectado_por_ia' | null;
          referencia_origem: string | null;
          id_documento_origem: string | null;
          data_original: string;
          data_ajustada: string;
          prioridade: 'baixa' | 'media' | 'alta' | 'critica';
          status: 'pendente' | 'em_andamento' | 'minuta_pronta' | 'concluido' | 'perdido';
          sala_guerra_ativada: boolean;
          sala_guerra_ativada_em: string | null;
          atribuido_a: string | null;
          backup_atribuido_a: string | null;
          minuta_automatica_gerada: boolean;
          id_documento_minuta_automatica: string | null;
          config_alertas: Json;
          alertas_enviados: Json;
          concluido_em: string | null;
          concluido_por: string | null;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          caso_id: number;
          tipo_prazo: string;
          descricao: string;
          origem?: 'publicacao' | 'intimacao' | 'contrato' | 'manual' | 'detectado_por_ia' | null;
          referencia_origem?: string | null;
          id_documento_origem?: string | null;
          data_original: string;
          data_ajustada: string;
          prioridade?: 'baixa' | 'media' | 'alta' | 'critica';
          status?: 'pendente' | 'em_andamento' | 'minuta_pronta' | 'concluido' | 'perdido';
          sala_guerra_ativada?: boolean;
          sala_guerra_ativada_em?: string | null;
          atribuido_a?: string | null;
          backup_atribuido_a?: string | null;
          minuta_automatica_gerada?: boolean;
          id_documento_minuta_automatica?: string | null;
          config_alertas?: Json;
          alertas_enviados?: Json;
          concluido_em?: string | null;
          concluido_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          caso_id?: number;
          tipo_prazo?: string;
          descricao?: string;
          origem?: 'publicacao' | 'intimacao' | 'contrato' | 'manual' | 'detectado_por_ia' | null;
          referencia_origem?: string | null;
          id_documento_origem?: string | null;
          data_original?: string;
          data_ajustada?: string;
          prioridade?: 'baixa' | 'media' | 'alta' | 'critica';
          status?: 'pendente' | 'em_andamento' | 'minuta_pronta' | 'concluido' | 'perdido';
          sala_guerra_ativada?: boolean;
          sala_guerra_ativada_em?: string | null;
          atribuido_a?: string | null;
          backup_atribuido_a?: string | null;
          minuta_automatica_gerada?: boolean;
          id_documento_minuta_automatica?: string | null;
          config_alertas?: Json;
          alertas_enviados?: Json;
          concluido_em?: string | null;
          concluido_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      tarefas_caso: {
        Row: {
          id: number;
          organizacao_id: string;
          caso_id: number;
          prazo_id: string | null;
          titulo: string;
          descricao: string | null;
          status: 'aberta' | 'em_andamento' | 'aguardando' | 'concluida' | 'cancelada';
          prioridade: 'baixa' | 'media' | 'alta' | 'critica';
          data_limite: string | null;
          iniciada_em: string | null;
          concluida_em: string | null;
          atribuida_a: string | null;
          origem: 'manual' | 'playbook' | 'sugerida_por_ia' | 'automatica_prazo' | null;
          id_passo_playbook: string | null;
          id_execucao_ia: string | null;
          criado_por: string | null;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: number;
          organizacao_id: string;
          caso_id: number;
          prazo_id?: string | null;
          titulo: string;
          descricao?: string | null;
          status?: 'aberta' | 'em_andamento' | 'aguardando' | 'concluida' | 'cancelada';
          prioridade?: 'baixa' | 'media' | 'alta' | 'critica';
          data_limite?: string | null;
          iniciada_em?: string | null;
          concluida_em?: string | null;
          atribuida_a?: string | null;
          origem?: 'manual' | 'playbook' | 'sugerida_por_ia' | 'automatica_prazo' | null;
          id_passo_playbook?: string | null;
          id_execucao_ia?: string | null;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: number;
          organizacao_id?: string;
          caso_id?: number;
          prazo_id?: string | null;
          titulo?: string;
          descricao?: string | null;
          status?: 'aberta' | 'em_andamento' | 'aguardando' | 'concluida' | 'cancelada';
          prioridade?: 'baixa' | 'media' | 'alta' | 'critica';
          data_limite?: string | null;
          iniciada_em?: string | null;
          concluida_em?: string | null;
          atribuida_a?: string | null;
          origem?: 'manual' | 'playbook' | 'sugerida_por_ia' | 'automatica_prazo' | null;
          id_passo_playbook?: string | null;
          id_execucao_ia?: string | null;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      documentos: {
        Row: {
          id: string;
          organizacao_id: string;
          caso_id: number | null;
          lead_id: string | null;
          titulo: string;
          descricao: string | null;
          tipo_documento: string | null;
          caminho_storage: string;
          nome_arquivo: string | null;
          tamanho_arquivo: number | null;
          tipo_mime: string | null;
          ocr_processado: boolean;
          texto_ocr: string | null;
          visibilidade: 'interno' | 'cliente' | 'convidado';
          contem_dados_pessoais: boolean;
          dados_pessoais_anonimizados: boolean;
          mapa_anonimizacao: Json | null;
          resumo_ia: string | null;
          entidades_ia: Json | null;
          classificacao_ia: Json | null;
          criado_por: string | null;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          caso_id?: number | null;
          lead_id?: string | null;
          titulo: string;
          descricao?: string | null;
          tipo_documento?: string | null;
          caminho_storage: string;
          nome_arquivo?: string | null;
          tamanho_arquivo?: number | null;
          tipo_mime?: string | null;
          ocr_processado?: boolean;
          texto_ocr?: string | null;
          visibilidade?: 'interno' | 'cliente' | 'convidado';
          contem_dados_pessoais?: boolean;
          dados_pessoais_anonimizados?: boolean;
          mapa_anonimizacao?: Json | null;
          resumo_ia?: string | null;
          entidades_ia?: Json | null;
          classificacao_ia?: Json | null;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          caso_id?: number | null;
          lead_id?: string | null;
          titulo?: string;
          descricao?: string | null;
          tipo_documento?: string | null;
          caminho_storage?: string;
          nome_arquivo?: string | null;
          tamanho_arquivo?: number | null;
          tipo_mime?: string | null;
          ocr_processado?: boolean;
          texto_ocr?: string | null;
          visibilidade?: 'interno' | 'cliente' | 'convidado';
          contem_dados_pessoais?: boolean;
          dados_pessoais_anonimizados?: boolean;
          mapa_anonimizacao?: Json | null;
          resumo_ia?: string | null;
          entidades_ia?: Json | null;
          classificacao_ia?: Json | null;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      nos_grafo_evidencias: {
        Row: {
          id: string;
          organizacao_id: string;
          caso_id: number;
          tipo_no: 'fato' | 'prova' | 'alegacao' | 'pedido' | 'base_legal' | 'risco';
          titulo: string;
          conteudo: string | null;
          referencias: Json | null;
          forca: number;
          gerado_por_ia: boolean;
          id_execucao_ia: string | null;
          confianca_ia: number | null;
          criado_por: string | null;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          caso_id: number;
          tipo_no: 'fato' | 'prova' | 'alegacao' | 'pedido' | 'base_legal' | 'risco';
          titulo: string;
          conteudo?: string | null;
          referencias?: Json | null;
          forca?: number;
          gerado_por_ia?: boolean;
          id_execucao_ia?: string | null;
          confianca_ia?: number | null;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          caso_id?: number;
          tipo_no?: 'fato' | 'prova' | 'alegacao' | 'pedido' | 'base_legal' | 'risco';
          titulo?: string;
          conteudo?: string | null;
          referencias?: Json | null;
          forca?: number;
          gerado_por_ia?: boolean;
          id_execucao_ia?: string | null;
          confianca_ia?: number | null;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      arestas_grafo_evidencias: {
        Row: {
          id: string;
          organizacao_id: string;
          caso_id: number;
          no_origem: string;
          no_destino: string;
          relacao: 'suportado_por' | 'depende_de' | 'fundamentado_por' | 'enfraquecido_por' | 'contradiz' | 'corrobora';
          peso: number;
          notas: string | null;
          gerado_por_ia: boolean;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          caso_id: number;
          no_origem: string;
          no_destino: string;
          relacao: 'suportado_por' | 'depende_de' | 'fundamentado_por' | 'enfraquecido_por' | 'contradiz' | 'corrobora';
          peso?: number;
          notas?: string | null;
          gerado_por_ia?: boolean;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          caso_id?: number;
          no_origem?: string;
          no_destino?: string;
          relacao?: 'suportado_por' | 'depende_de' | 'fundamentado_por' | 'enfraquecido_por' | 'contradiz' | 'corrobora';
          peso?: number;
          notas?: string | null;
          gerado_por_ia?: boolean;
          criado_em?: string;
        };
      };
      execucoes_agente: {
        Row: {
          id: string;
          organizacao_id: string;
          tipo_agente: string;
          versao_agente: string | null;
          nivel_autonomia: 'A0' | 'A1' | 'A2' | 'A3';
          nivel_risco: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          tipo_gatilho: 'evento' | 'manual' | 'agendado' | 'encadeado' | null;
          id_evento_gatilho: string | null;
          tipo_entidade_gatilho: string | null;
          id_entidade_gatilho: string | null;
          dados_entrada: Json | null;
          dados_saida: Json | null;
          pontuacao_confianca: number | null;
          pontuacao_fundamentacao: number | null;
          pontuacao_consistencia: number | null;
          iniciado_em: string;
          finalizado_em: string | null;
          duracao_ms: number | null;
          status: 'na_fila' | 'executando' | 'concluido' | 'falhou' | 'cancelado';
          mensagem_erro: string | null;
          feedback_humano: 'aceito' | 'modificado' | 'rejeitado' | null;
          feedback_humano_por: string | null;
          feedback_humano_em: string | null;
          notas_feedback_humano: string | null;
          nome_modelo: string | null;
          versao_modelo: string | null;
          hash_prompt: string | null;
          base_legal: string | null;
          finalidade: string | null;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          tipo_agente: string;
          versao_agente?: string | null;
          nivel_autonomia: 'A0' | 'A1' | 'A2' | 'A3';
          nivel_risco?: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          tipo_gatilho?: 'evento' | 'manual' | 'agendado' | 'encadeado' | null;
          id_evento_gatilho?: string | null;
          tipo_entidade_gatilho?: string | null;
          id_entidade_gatilho?: string | null;
          dados_entrada?: Json | null;
          dados_saida?: Json | null;
          pontuacao_confianca?: number | null;
          pontuacao_fundamentacao?: number | null;
          pontuacao_consistencia?: number | null;
          iniciado_em?: string;
          finalizado_em?: string | null;
          duracao_ms?: number | null;
          status?: 'na_fila' | 'executando' | 'concluido' | 'falhou' | 'cancelado';
          mensagem_erro?: string | null;
          feedback_humano?: 'aceito' | 'modificado' | 'rejeitado' | null;
          feedback_humano_por?: string | null;
          feedback_humano_em?: string | null;
          notas_feedback_humano?: string | null;
          nome_modelo?: string | null;
          versao_modelo?: string | null;
          hash_prompt?: string | null;
          base_legal?: string | null;
          finalidade?: string | null;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          tipo_agente?: string;
          versao_agente?: string | null;
          nivel_autonomia?: 'A0' | 'A1' | 'A2' | 'A3';
          nivel_risco?: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          tipo_gatilho?: 'evento' | 'manual' | 'agendado' | 'encadeado' | null;
          id_evento_gatilho?: string | null;
          tipo_entidade_gatilho?: string | null;
          id_entidade_gatilho?: string | null;
          dados_entrada?: Json | null;
          dados_saida?: Json | null;
          pontuacao_confianca?: number | null;
          pontuacao_fundamentacao?: number | null;
          pontuacao_consistencia?: number | null;
          iniciado_em?: string;
          finalizado_em?: string | null;
          duracao_ms?: number | null;
          status?: 'na_fila' | 'executando' | 'concluido' | 'falhou' | 'cancelado';
          mensagem_erro?: string | null;
          feedback_humano?: 'aceito' | 'modificado' | 'rejeitado' | null;
          feedback_humano_por?: string | null;
          feedback_humano_em?: string | null;
          notas_feedback_humano?: string | null;
          nome_modelo?: string | null;
          versao_modelo?: string | null;
          hash_prompt?: string | null;
          base_legal?: string | null;
          finalidade?: string | null;
          criado_em?: string;
        };
      };
      sugestoes_ia: {
        Row: {
          id: string;
          organizacao_id: string;
          id_execucao_ia: string;
          tipo_sugestao: string;
          titulo: string;
          resumo: string;
          razao: string | null;
          estruturado: Json | null;
          confianca: number | null;
          pontuacao_fundamentacao: number | null;
          pontuacao_acionabilidade: number | null;
          pontuacao_risco: number | null;
          status: 'pendente' | 'aceita' | 'modificada' | 'rejeitada' | 'expirada';
          acionada_por: string | null;
          acionada_em: string | null;
          notas_acao: string | null;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          id_execucao_ia: string;
          tipo_sugestao: string;
          titulo: string;
          resumo: string;
          razao?: string | null;
          estruturado?: Json | null;
          confianca?: number | null;
          pontuacao_fundamentacao?: number | null;
          pontuacao_acionabilidade?: number | null;
          pontuacao_risco?: number | null;
          status?: 'pendente' | 'aceita' | 'modificada' | 'rejeitada' | 'expirada';
          acionada_por?: string | null;
          acionada_em?: string | null;
          notas_acao?: string | null;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          id_execucao_ia?: string;
          tipo_sugestao?: string;
          titulo?: string;
          resumo?: string;
          razao?: string | null;
          estruturado?: Json | null;
          confianca?: number | null;
          pontuacao_fundamentacao?: number | null;
          pontuacao_acionabilidade?: number | null;
          pontuacao_risco?: number | null;
          status?: 'pendente' | 'aceita' | 'modificada' | 'rejeitada' | 'expirada';
          acionada_por?: string | null;
          acionada_em?: string | null;
          notas_acao?: string | null;
          criado_em?: string;
        };
      };
      acoes: {
        Row: {
          id: string;
          organizacao_id: string;
          tipo_entidade: string;
          id_entidade: string;
          tipo_acao: string;
          parametros_acao: Json | null;
          origem: 'manual' | 'sugerida_por_ia' | 'playbook' | 'automacao' | null;
          id_sugestao_ia: string | null;
          status: 'proposta' | 'em_aprovacao' | 'aprovada' | 'executada' | 'cancelada' | 'rejeitada';
          requer_aprovacao: boolean;
          papeis_aprovadores_requeridos: string[] | null;
          aprovada_por: string | null;
          aprovada_em: string | null;
          notas_aprovacao: string | null;
          executada_por: string | null;
          executada_em: string | null;
          resultado_execucao: Json | null;
          rejeitada_por: string | null;
          rejeitada_em: string | null;
          motivo_rejeicao: string | null;
          criado_por: string | null;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          tipo_entidade: string;
          id_entidade: string;
          tipo_acao: string;
          parametros_acao?: Json | null;
          origem?: 'manual' | 'sugerida_por_ia' | 'playbook' | 'automacao' | null;
          id_sugestao_ia?: string | null;
          status?: 'proposta' | 'em_aprovacao' | 'aprovada' | 'executada' | 'cancelada' | 'rejeitada';
          requer_aprovacao?: boolean;
          papeis_aprovadores_requeridos?: string[] | null;
          aprovada_por?: string | null;
          aprovada_em?: string | null;
          notas_aprovacao?: string | null;
          executada_por?: string | null;
          executada_em?: string | null;
          resultado_execucao?: Json | null;
          rejeitada_por?: string | null;
          rejeitada_em?: string | null;
          motivo_rejeicao?: string | null;
          criado_por?: string | null;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          tipo_entidade?: string;
          id_entidade?: string;
          tipo_acao?: string;
          parametros_acao?: Json | null;
          origem?: 'manual' | 'sugerida_por_ia' | 'playbook' | 'automacao' | null;
          id_sugestao_ia?: string | null;
          status?: 'proposta' | 'em_aprovacao' | 'aprovada' | 'executada' | 'cancelada' | 'rejeitada';
          requer_aprovacao?: boolean;
          papeis_aprovadores_requeridos?: string[] | null;
          aprovada_por?: string | null;
          aprovada_em?: string | null;
          notas_aprovacao?: string | null;
          executada_por?: string | null;
          executada_em?: string | null;
          resultado_execucao?: Json | null;
          rejeitada_por?: string | null;
          rejeitada_em?: string | null;
          motivo_rejeicao?: string | null;
          criado_por?: string | null;
          criado_em?: string;
        };
      };
      logs_auditoria: {
        Row: {
          id: string;
          organizacao_id: string;
          tipo_ator: 'usuario' | 'agente' | 'sistema' | null;
          id_usuario_ator: string | null;
          tipo_agente_ator: string | null;
          evento: string;
          categoria_evento: string | null;
          tipo_entidade: string | null;
          id_entidade: string | null;
          dados_antes: Json | null;
          dados_depois: Json | null;
          dados_diff: Json | null;
          endereco_ip: string | null;
          agente_usuario: string | null;
          id_execucao_ia: string | null;
          id_acao: string | null;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          tipo_ator?: 'usuario' | 'agente' | 'sistema' | null;
          id_usuario_ator?: string | null;
          tipo_agente_ator?: string | null;
          evento: string;
          categoria_evento?: string | null;
          tipo_entidade?: string | null;
          id_entidade?: string | null;
          dados_antes?: Json | null;
          dados_depois?: Json | null;
          dados_diff?: Json | null;
          endereco_ip?: string | null;
          agente_usuario?: string | null;
          id_execucao_ia?: string | null;
          id_acao?: string | null;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          tipo_ator?: 'usuario' | 'agente' | 'sistema' | null;
          id_usuario_ator?: string | null;
          tipo_agente_ator?: string | null;
          evento?: string;
          categoria_evento?: string | null;
          tipo_entidade?: string | null;
          id_entidade?: string | null;
          dados_antes?: Json | null;
          dados_depois?: Json | null;
          dados_diff?: Json | null;
          endereco_ip?: string | null;
          agente_usuario?: string | null;
          id_execucao_ia?: string | null;
          id_acao?: string | null;
          criado_em?: string;
        };
      };
      perfis_juiz: {
        Row: {
          id: string;
          nome: string;
          tribunal: string;
          unidade: string | null;
          cargo: string | null;
          estatisticas: Json;
          padroes_por_materia: Json;
          preferencias: Json;
          insights: Json;
          janela_dados_meses: number;
          tamanho_amostra: number | null;
          ultima_atualizacao: string;
          frequencia_atualizacao: string;
          fontes_dados: Json;
        };
        Insert: {
          id?: string;
          nome: string;
          tribunal: string;
          unidade?: string | null;
          cargo?: string | null;
          estatisticas?: Json;
          padroes_por_materia?: Json;
          preferencias?: Json;
          insights?: Json;
          janela_dados_meses?: number;
          tamanho_amostra?: number | null;
          ultima_atualizacao?: string;
          frequencia_atualizacao?: string;
          fontes_dados?: Json;
        };
        Update: {
          id?: string;
          nome?: string;
          tribunal?: string;
          unidade?: string | null;
          cargo?: string | null;
          estatisticas?: Json;
          padroes_por_materia?: Json;
          preferencias?: Json;
          insights?: Json;
          janela_dados_meses?: number;
          tamanho_amostra?: number | null;
          ultima_atualizacao?: string;
          frequencia_atualizacao?: string;
          fontes_dados?: Json;
        };
      };
      playbooks: {
        Row: {
          id: string;
          organizacao_id: string | null;
          nome: string;
          descricao: string | null;
          condicoes_gatilho: Json | null;
          area_juridica: string[] | null;
          tipos_caso: string[] | null;
          ativo: boolean;
          e_modelo: boolean;
          duracao_estimada_horas: number | null;
          taxa_sucesso: number | null;
          vezes_usado: number;
          criado_por: string | null;
          criado_em: string;
          atualizado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id?: string | null;
          nome: string;
          descricao?: string | null;
          condicoes_gatilho?: Json | null;
          area_juridica?: string[] | null;
          tipos_caso?: string[] | null;
          ativo?: boolean;
          e_modelo?: boolean;
          duracao_estimada_horas?: number | null;
          taxa_sucesso?: number | null;
          vezes_usado?: number;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string | null;
          nome?: string;
          descricao?: string | null;
          condicoes_gatilho?: Json | null;
          area_juridica?: string[] | null;
          tipos_caso?: string[] | null;
          ativo?: boolean;
          e_modelo?: boolean;
          duracao_estimada_horas?: number | null;
          taxa_sucesso?: number | null;
          vezes_usado?: number;
          criado_por?: string | null;
          criado_em?: string;
          atualizado_em?: string;
        };
      };
      sinais_oportunidade: {
        Row: {
          id: string;
          organizacao_id: string;
          caso_id: number;
          tipo_sinal: 'pressao_financeira' | 'pressao_prazo' | 'lacuna_prova' | 'precedente_favoravel' | 'fraqueza_oponente' | 'janela_acordo' | 'oportunidade_urgencia' | 'momento_estrategico';
          titulo: string;
          descricao: string | null;
          acao_recomendada: string | null;
          timing_recomendado: string | null;
          confianca: number | null;
          impacto_potencial: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          detectado_em: string;
          expira_em: string | null;
          expirado: boolean;
          acao_tomada: boolean;
          acao_tomada_em: string | null;
          resultado_acao: string | null;
          dados_fonte: Json | null;
          id_execucao_ia: string | null;
          criado_em: string;
        };
        Insert: {
          id?: string;
          organizacao_id: string;
          caso_id: number;
          tipo_sinal: 'pressao_financeira' | 'pressao_prazo' | 'lacuna_prova' | 'precedente_favoravel' | 'fraqueza_oponente' | 'janela_acordo' | 'oportunidade_urgencia' | 'momento_estrategico';
          titulo: string;
          descricao?: string | null;
          acao_recomendada?: string | null;
          timing_recomendado?: string | null;
          confianca?: number | null;
          impacto_potencial?: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          detectado_em?: string;
          expira_em?: string | null;
          expirado?: boolean;
          acao_tomada?: boolean;
          acao_tomada_em?: string | null;
          resultado_acao?: string | null;
          dados_fonte?: Json | null;
          id_execucao_ia?: string | null;
          criado_em?: string;
        };
        Update: {
          id?: string;
          organizacao_id?: string;
          caso_id?: number;
          tipo_sinal?: 'pressao_financeira' | 'pressao_prazo' | 'lacuna_prova' | 'precedente_favoravel' | 'fraqueza_oponente' | 'janela_acordo' | 'oportunidade_urgencia' | 'momento_estrategico';
          titulo?: string;
          descricao?: string | null;
          acao_recomendada?: string | null;
          timing_recomendado?: string | null;
          confianca?: number | null;
          impacto_potencial?: 'baixo' | 'medio' | 'alto' | 'critico' | null;
          detectado_em?: string;
          expira_em?: string | null;
          expirado?: boolean;
          acao_tomada?: boolean;
          acao_tomada_em?: string | null;
          resultado_acao?: string | null;
          dados_fonte?: Json | null;
          id_execucao_ia?: string | null;
          criado_em?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      e_membro_de: {
        Args: {
          org_id: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
